"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Stack_1 = require("./Stack");
var Queue_1 = require("./Queue");
var stack = new Stack_1.Stack();
// @ts-ignore
var queue = new Queue_1.Queue();
stack.pushData(1);
stack.pushData(2);
stack.pushData(3);
stack.pushData(4);
stack.pushData(5);
stack.pushData(5);
stack.pushData(4);
stack.pushData(3);
stack.pushData(2);
stack.pushData(1);
queue.enqueue(1);
queue.enqueue(2);
queue.enqueue(3);
queue.enqueue(4);
queue.enqueue(5);
queue.enqueue(5);
queue.enqueue(4);
queue.enqueue(3);
queue.enqueue(2);
queue.enqueue(1);
stack.readdata();
console.log(stack);
console.log(stack);
stack.readdata();
console.log(stack);
